version: '3.7'

services:
  run-up-redis:
    image: redis
    container_name: run-up-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - cache-network

networks:
  cache-network:
    driver: bridge
    name: cache-network

volumes:
  redis-data:
